const images = {
  bg: require('../../assets/images/bg.png'),
  splashIcon: require('../../assets/images/splash-icon.png'),
  image: require('../../assets/images/image.png'),
  homeImage: require('../../assets/images/home-image.png'),
  depositImage: require('../../assets/images/deposit-image.png'),
  profile: require('../../assets/images/profile.png'),
  primaryDeposit: require('../../assets/images/primary-deposit.png'),
  greyDeposit: require('../../assets/images/grey-deposit.png'),
  primaryLoans: require('../../assets/images/primary-loans.png'),
  greyLoans: require('../../assets/images/grey-loans.png'),
  services1: require('../../assets/images/services1.png'),
  services2: require('../../assets/images/services2.png'),
  services3: require('../../assets/images/services3.png'),
  services4: require('../../assets/images/services4.png'),
  services5: require('../../assets/images/services5.png'),
  services6: require('../../assets/images/services6.png'),
  services7: require('../../assets/images/services7.png'),
  services8: require('../../assets/images/services8.png'),
  services9: require('../../assets/images/services9.png'),
  services10: require('../../assets/images/services10.png'),
  services11: require('../../assets/images/services11.png'),
  services12: require('../../assets/images/services12.png'),
  services13: require('../../assets/images/services13.png'),
  transaction1: require('../../assets/images/transaction1.png'),
  transaction2: require('../../assets/images/transaction2.png'),
  loan1: require('../../assets/images/loan1.png'),
  loan2: require('../../assets/images/loan2.png'),
  loan3: require('../../assets/images/loan3.png'),
  loan4: require('../../assets/images/loan4.png'),
  image2: require('../../assets/images/image2.png'),
  onboarding1: require('../../assets/images/onboarding1.png'),
  onboarding2: require('../../assets/images/onboarding2.png'),
  onboarding3: require('../../assets/images/onboarding3.png'),
};

export default images;
